// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-RsqN9Tsg46c-ibaOOtfel4NC-H9Erk',
    appId: '1:131105019330:web:5f5676a9935b241570725b',
    messagingSenderId: '131105019330',
    projectId: 'opinion-8509e',
    authDomain: 'opinion-8509e.firebaseapp.com',
    storageBucket: 'opinion-8509e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMhlOZ2lvT7VOZROAR7APOWGHfxn3GT4',
    appId: '1:131105019330:android:d90463a12e9f9c4f70725b',
    messagingSenderId: '131105019330',
    projectId: 'opinion-8509e',
    storageBucket: 'opinion-8509e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBX33KCb8WtTnDGthRLLYoSrpUGNEv0k',
    appId: '1:131105019330:ios:c59f8d37d035be8170725b',
    messagingSenderId: '131105019330',
    projectId: 'opinion-8509e',
    storageBucket: 'opinion-8509e.appspot.com',
    iosClientId: '131105019330-15ob2rqbmt8ualltm4nbkdc9qvi0hjk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.opinion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBX33KCb8WtTnDGthRLLYoSrpUGNEv0k',
    appId: '1:131105019330:ios:448ccbc032b6364570725b',
    messagingSenderId: '131105019330',
    projectId: 'opinion-8509e',
    storageBucket: 'opinion-8509e.appspot.com',
    iosClientId: '131105019330-5ctvtd1uh24a9i6s5225eu3f45bf81kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.opinion.RunnerTests',
  );
}
